---
title: "Day 11 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

## Part 1
I know this is wrong, and yet - here goes the brute force attempt

```{r}
blink<-function(n,r){
  while(r>0){
    n<-sapply(n,function(x){
      if(x==0){y<-1
      }else if(nchar(x)%%2==0){
        d<-nchar(x)/2
        y<-c(x%/%(10^d),x%%(10^d))
      }else{y<-x*2024}
      y})
    ### needed because splitting in two stones turns it
    ### into a matrix for reasons I do not understand  this stops that.
    n<-unlist(n)
    r<-r-1}
  length(n)}
```


```{r}
part1<-blink(c(125,17),25)
part1
```

## Part 2

damn lanternfish

```{r}
blinkinglanternfish<-function(r,n){
  ### first, change n into a df
    n<-as.data.frame(cbind(n,rep(1,length(n))))
    colnames(n)<-c("val","cnt")
    while(r>0){
    ### create a blank dataframe
    nxt<-as.data.frame(matrix(nrow=0,ncol=2))
    ### apply the rule to each row in the original frame and put the output in the new frame
    for(i in 1:nrow(n)){
      if(n$val[i]==0){
        nxt<-rbind(nxt,c(1,n$cnt[i]))
      }else if(nchar(n$val[i])%%2==0){
        d<-nchar(n$val[i])/2
        a<-n$val[i]%/%(10^d)
        b<-n$val[i]%%(10^d)
        nxt<-rbind(nxt,c(a,n$cnt[i]))
        nxt<-rbind(nxt,c(b,n$cnt[i]))
      }else{
        nxt<-rbind(nxt,c(n$val[i]*2024,n$cnt[i]))}
    ### update the column names
    colnames(nxt)<-c("val","cnt")}
    ### summarize the columns so each value has the number of times that value appears on a stone.
    n<-nxt%>% group_by(val)%>%summarise(cnt=sum(cnt))
    r<-r-1}
stones<-sum(n$cnt)
stones}
  
  
```

```{r}
part2<-blinkinglanternfish(75,c(125,17))
part2
```

65601038650482