---
title: "Day 13 Notebook"
output: html_notebook
---

```{r setup, include=FALSE}
library(ggplot2)
library(reshape2)
library(knitr)
library(dplyr)
library(stringr)
library(tidyverse)
library(readr)
library(collections)
options(scipen = 999)
```

```{r}
input<-read_lines("Day13Sample.txt")

### find how many prizes
p<-c(0,which(input==""))+1
### pull numbers out of the input
inputnumbers<-lapply(input,function(x){as.numeric(unlist(str_extract_all(x,"\\d+")))})
### set up machines in an easy way to solve them
machines<-list()
for(i in 1:length(p)){
  a<-rbind(c(inputnumbers[[p[i]]][1],inputnumbers[[p[i]+1]][1]),
           c(inputnumbers[[p[i]]][2],inputnumbers[[p[i]+1]][2]))
  b<-inputnumbers[[p[i]+2]]
  prmach<-list(a,b)
  machines<-c(machines,list(prmach))}

```

This moves:
```
Button A: X+94, Y+34
Button B: X+22, Y+67
Prize: X=8400, Y=5400
```
to

\[\left(\begin{array}{cc} 
94 & 22\\
34 & 67
\end{array}\right)
\left(\begin{array}{cc} 
8400\\5400
\end{array}\right)\]

 
so that it can be put into solve().\\
Solve() did not work, but the formatting did.

## Part 1

Determinants ftw.

```{r}
getprizes<-function(m){
  d<-sapply(m,function(x){
   ab<-x[[1]]
   ab<-(ab[1,1]*ab[2,2])-(ab[2,1]*ab[1,2])
   ab})
  dx<-sapply(m,function(x){
    xm<-cbind(x[[2]],x[[1]][,2])
    xm<-(xm[1,1]*xm[2,2])-(xm[2,1]*xm[1,2])
    xm})
  dy<-sapply(m,function(x){
    ym<-cbind(x[[1]][,1],x[[2]])
    ym<-(ym[1,1]*ym[2,2])-(ym[2,1]*ym[1,2])
    ym})
  tokens<-0
  ## find a
  a<-dx%/%d
  aa<-dx/d
  ## find b
  b<-dy%/%d
  bb<-dy/d
  ## filter out the ones that aren't integers and are over 100
  ok<-intersect(intersect(intersect(which(a==aa),which(b==bb)),which(a<=100)),which(b<=100))
  ### tokens = 3*a+b
  tokens<-sum(3*a[ok]+b[ok])
  tokens}
  
```

```{r}
getprizes(machines)
```
## Part 2
Same as part 1, but add 10000000000000 to the solution

```{r}
farawayprizes<-function(m){
  d<-sapply(m,function(x){
   ab<-x[[1]]
   ab<-(ab[1,1]*ab[2,2])-(ab[2,1]*ab[1,2])
   ab})
  dx<-sapply(m,function(x){
    xm<-cbind(x[[2]]+10000000000000,x[[1]][,2])
    xm<-(xm[1,1]*xm[2,2])-(xm[2,1]*xm[1,2])
    xm})
  dy<-sapply(m,function(x){
    ym<-cbind(x[[1]][,1],x[[2]]+10000000000000)
    ym<-(ym[1,1]*ym[2,2])-(ym[2,1]*ym[1,2])
    ym})
  tokens<-0
  a<-dx%/%d
  aa<-dx/d
  b<-dy%/%d
  bb<-dy/d
  ok<-intersect(which(a==aa),which(b==bb))
  tokens<-sum(3*a[ok]+b[ok])
  tokens}
  
```

```{r}
farawayprizes(machines)
```
